package com.pfa.tracabilite_ia.exception;

public enum OpenRouterErrorCode {
    OPENROUTER_AUTHENTICATION_FAILED,
    OPENROUTER_CREDIT_ERROR,
    OPENROUTER_RATE_LIMITED,
    OPENROUTER_MODEL_NOT_FOUND,
    OPENROUTER_TIMEOUT,
    OPENROUTER_UNAVAILABLE,
    OPENROUTER_INVALID_RESPONSE,
    MODEL_UNAVAILABLE
}
