package com.pfa.tracabilite_ia.enumeration;

public enum DecisionHistoryAction {
    DECISION_CREATED,
    ML_ANALYSIS_STARTED,
    ML_ANALYSIS_COMPLETED,
    ML_ANALYSIS_FAILED,
    OPENROUTER_ANALYSIS_STARTED,
    AGENT_RESPONSE_SUCCESS,
    AGENT_RESPONSE_FAILED,
    CONSENSUS_CALCULATED,
    DECISION_SUBMITTED_FOR_VALIDATION,
    DECISION_APPROVED,
    DECISION_REJECTED,
    DECISION_MODIFIED,
    DECISION_REVIEWED,
    SOURCE_ADDED,
    SOURCE_REMOVED,
    INTEGRITY_VERIFIED,
    DECISION_ARCHIVED
}
